/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package selectmovie;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.ButtonGroup;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author C0472359
 */
public class ConfirmBuy extends javax.swing.JDialog {
   
    private Movie theMovie;

    
    /**
     * Creates new form java
     */
    public ConfirmBuy(JFrame f, boolean m, Movie theMovie) {
        
        super(f, m);
        initComponents();
        this.jLabelMovieName.setText(theMovie.getMovieName());
        this.jLabelRating.setText(theMovie.getRating());
        //this.jLabelActors.setText(theMovie.getActors()); 
        //this.jLabelOrder.setText(theMovie.getOrderItem());
        /* THIS IS BIDDING NUMBERS */
        Integer startValue = 1;
        Integer minValue = 0;
        Integer maxValue = 10;
        Integer stepValue = 1;
        SpinnerModel numModel = new SpinnerNumberModel(startValue, minValue, maxValue, stepValue);
        SpinnerModel numModel1 = new SpinnerNumberModel(startValue, minValue, maxValue, stepValue);
        SpinnerModel numModel2 = new SpinnerNumberModel(startValue, minValue, maxValue, stepValue);
        jSpinnerChild.setModel(numModel);
        jSpinnerAdult.setModel(numModel1);
        jSpinnerSenior.setModel(numModel2);
        
        
        ButtonGroup timeGroup = new ButtonGroup();
        timeGroup.add(jRadioTime);
        timeGroup.add(jRadioTime2);        
        
        jLabelChildPrice.setText("8");
        jLabelAdultPrice.setText("11");
        jLabelSeniorPrice.setText("10");
        
        jLabelAvail.setVisible(false);
        jLabelFull.setVisible(false);
        
    }
    /*
    void setTicketCount(int ticketCount){
        JLabel
    }
    
    */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        jLabelMovieName = new javax.swing.JLabel();
        jLabelRating = new javax.swing.JLabel();
        jSpinnerChild = new javax.swing.JSpinner();
        jButtonSave = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jLabelChild = new javax.swing.JLabel();
        jLabelAdult = new javax.swing.JLabel();
        jSpinnerAdult = new javax.swing.JSpinner();
        jLabelSenior = new javax.swing.JLabel();
        jSpinnerSenior = new javax.swing.JSpinner();
        jLabelRate = new javax.swing.JLabel();
        jComboBoxType = new javax.swing.JComboBox<>();
        jLabelType = new javax.swing.JLabel();
        jLabelChildPrice = new javax.swing.JLabel();
        jLabelAdultPrice = new javax.swing.JLabel();
        jLabelSeniorPrice = new javax.swing.JLabel();
        jLabelPrice = new javax.swing.JLabel();
        jLabelQuantity = new javax.swing.JLabel();
        jRadioTime = new javax.swing.JRadioButton();
        jRadioTime2 = new javax.swing.JRadioButton();
        jLabelSubtotal = new javax.swing.JLabel();
        jLabelTotalNo = new javax.swing.JLabel();
        jLabelAdultTotal = new javax.swing.JLabel();
        jLabelSeniorTotal = new javax.swing.JLabel();
        jLabelTotal = new javax.swing.JLabel();
        jLabelChildTotal = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonPay = new javax.swing.JButton();
        jTextCard = new javax.swing.JTextField();
        jTextCVC = new javax.swing.JTextField();
        jTextExpDate = new javax.swing.JTextField();
        jLabelStatus = new javax.swing.JLabel();
        jLabelAvail = new javax.swing.JLabel();
        jLabelFull = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Place order on selected movie");
        setBackground(java.awt.Color.lightGray);

        jLabelMovieName.setBackground(java.awt.Color.white);
        jLabelMovieName.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 36)); // NOI18N
        jLabelMovieName.setText("Movie Name");

        jLabelRating.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jLabelRating.setText("Rating");

        jSpinnerChild.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jSpinnerChild.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jSpinnerChildInputMethodTextChanged(evt);
            }
        });

        jButtonSave.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jButtonSave.setText("Update price");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jButtonCancel.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jLabelChild.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jLabelChild.setText("Child:");

        jLabelAdult.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jLabelAdult.setText("Adult:");

        jSpinnerAdult.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N

        jLabelSenior.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jLabelSenior.setText("Senior:");

        jSpinnerSenior.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N

        jLabelRate.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jLabelRate.setText("Rate:");

        jComboBoxType.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jComboBoxType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Regular", "Matinee", "Tuesday" }));
        jComboBoxType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTypeActionPerformed(evt);
            }
        });

        jLabelType.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jLabelType.setText("Type:");

        jLabelChildPrice.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jLabelChildPrice.setText("$8");

        jLabelAdultPrice.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jLabelAdultPrice.setText("$7");

        jLabelSeniorPrice.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jLabelSeniorPrice.setText("$11");

        jLabelPrice.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jLabelPrice.setText("Price:");

        jLabelQuantity.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jLabelQuantity.setText("Quantity:");

        jRadioTime.setText("10:00 am ");
        jRadioTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioTimeActionPerformed(evt);
            }
        });

        jRadioTime2.setText("6:00 pm");
        jRadioTime2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioTime2ActionPerformed(evt);
            }
        });

        jLabelSubtotal.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jLabelSubtotal.setText("Subtotal");

        jLabelTotalNo.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jLabelTotalNo.setText("0");

        jLabelAdultTotal.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jLabelAdultTotal.setText("0");

        jLabelSeniorTotal.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jLabelSeniorTotal.setText("0");

        jLabelTotal.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jLabelTotal.setText("Total:");

        jLabelChildTotal.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jLabelChildTotal.setText("0");

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(0));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Yu Gothic Light", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 255));
        jLabel1.setText("Card number ");

        jLabel2.setFont(new java.awt.Font("Source Sans Pro Black", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 255, 255));
        jLabel2.setText("CVC");

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 255, 255));
        jLabel3.setText("Expiry Date:");

        jButtonPay.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jButtonPay.setText("Pay now");
        jButtonPay.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPayActionPerformed(evt);
            }
        });

        jTextCard.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        jTextCard.setText("1234567891234567");
        jTextCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCardActionPerformed(evt);
            }
        });

        jTextCVC.setText("123");
        jTextCVC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCVCActionPerformed(evt);
            }
        });

        jTextExpDate.setText("01/45");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))))
                .addGap(72, 72, 72)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextCard, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                    .addComponent(jTextCVC)
                    .addComponent(jTextExpDate))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 409, Short.MAX_VALUE)
                .addComponent(jButtonPay, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(346, 346, 346))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jTextCard, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextCVC, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextExpDate, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(jButtonPay)
                .addGap(28, 28, 28))
        );

        jLabelStatus.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jLabelStatus.setText("Movie Status:");

        jLabelAvail.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jLabelAvail.setForeground(new java.awt.Color(0, 153, 0));
        jLabelAvail.setText("Available");

        jLabelFull.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jLabelFull.setForeground(new java.awt.Color(255, 0, 51));
        jLabelFull.setText("Full");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelMovieName, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(400, 400, 400)
                                        .addComponent(jLabelTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(31, 31, 31)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelSeniorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelTotalNo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButtonCancel)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelChild, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelSenior)
                                            .addComponent(jLabelAdult)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabelRate)
                                                .addGap(125, 125, 125)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabelPrice)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jLabelAdultPrice)
                                                            .addComponent(jLabelChildPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(14, 14, 14)
                                                        .addComponent(jLabelSeniorPrice)))))
                                        .addGap(84, 84, 84)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabelRating, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jLabelQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jSpinnerChild, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jSpinnerAdult, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGap(79, 79, 79)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jLabelAdultTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jLabelChildTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jLabelSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addGap(235, 235, 235))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabelAvail, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(48, 48, 48)))
                                        .addComponent(jLabelFull, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelType)
                                        .addGap(18, 18, 18)
                                        .addComponent(jComboBoxType, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(162, 162, 162)
                                        .addComponent(jRadioTime)
                                        .addGap(33, 33, 33)
                                        .addComponent(jRadioTime2)
                                        .addGap(93, 93, 93)
                                        .addComponent(jLabelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(272, 272, 272)
                                            .addComponent(jSpinnerSenior, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(149, 149, 149))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jButtonSave)
                                            .addGap(139, 139, 139))))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMovieName, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelRating, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelType)
                    .addComponent(jComboBoxType, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioTime)
                    .addComponent(jRadioTime2)
                    .addComponent(jLabelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAvail, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFull, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRate)
                    .addComponent(jLabelPrice)
                    .addComponent(jLabelQuantity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelAdultPrice)
                            .addComponent(jSpinnerAdult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelAdultTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jSpinnerChild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelChildPrice)
                        .addComponent(jLabelChildTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabelChild)
                        .addGap(51, 51, 51)
                        .addComponent(jLabelAdult)
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelSenior)
                            .addComponent(jLabelSeniorPrice)
                            .addComponent(jSpinnerSenior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelSeniorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTotalNo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSave)
                    .addComponent(jButtonCancel))
                .addGap(46, 46, 46)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/*
    private void JTextNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextNameActionPerformed
        // TODO add your handlifdfng code here:
    }//GEN-LAST:event_JTextNameActionPerformed
*/
    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        
        Integer childTotal = Integer.parseInt(jLabelChildPrice.getText()) * ((int)jSpinnerChild.getValue());
        jLabelChildTotal.setText("" + childTotal);
        Integer adultTotal = Integer.parseInt(jLabelAdultPrice.getText()) * ((int)jSpinnerAdult.getValue());
        jLabelAdultTotal.setText("" + adultTotal);
        Integer seniorTotal = Integer.parseInt(jLabelSeniorPrice.getText()) * ((int)jSpinnerSenior.getValue());
        jLabelSeniorTotal.setText("" + seniorTotal);
        
        Integer totals = childTotal + adultTotal + seniorTotal;
        jLabelTotalNo.setText(totals.toString());
// modififed april 10 why is school killing me T^
       //System.out.println(jSpinner1.getValue());
       //System.out.println("hee");
      
        /*
        //String filename ="\\src\\selectcontract\\output_bid.txt";
        String filename ="M:\\125Sadness\\ICS125Project\\JavaApplication1\\src\\selectmovie\\output_movie.txt";
        
        //THIS IS ORDER SUMMARY 
        try {
            FileWriter fileWriter = new FileWriter(filename);
            BufferedWriter br = new BufferedWriter(fileWriter);
            
            String movieName = jLabelMovieName.getText();
            int total=0;
            int count=0;
            int childAmount=0;
            int adultAmount=0;
            int seniorAmount=0;
            // REGULAR */
            
        
            //System.out.print("Total of tickets is:" + count);
            //Integer totalMoney = childAmount + adultAmount + seniorTotal;
            // ArrayList<> priceType = jComboBoxType<>.getText();
            //String rate= jLabelRate.getText();
            //String total = jLabelTotal.getText();
                
            //br.append(name);
            //br.append(movieName);
           // br.append(totalMoney.toString());

            //fileWriter.close();
       
       // } catch(IOException ex){
          //  System.out.println(ex.getMessage());
        
          //jLabelChildTotal.setText(.toString());
    
        //dispose();    
    }//GEN-LAST:event_jButtonSaveActionPerformed
       void addCheckoutListener(ActionListener listenForCheckoutButton){
        //JBidButton.addActionListener(listenForBidButton);
        jButtonPay.addActionListener(listenForCheckoutButton);
    }
    private void jComboBoxTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTypeActionPerformed
        // TODO add your handling code here:
           //THIS WORKS !!! 
       if(jComboBoxType.getSelectedItem().equals("Regular")){
            jLabelChildPrice.setText("8");
            jLabelAdultPrice.setText("11");
            jLabelSeniorPrice.setText("10");
       } else if (jComboBoxType.getSelectedItem().equals("Matinee")) {
           jLabelChildPrice.setText("7");
            jLabelAdultPrice.setText("7");
            jLabelSeniorPrice.setText("7");
       } else if (jComboBoxType.getSelectedItem().equals("Tuesday")) {
           jLabelChildPrice.setText("10");
            jLabelAdultPrice.setText("14");
            jLabelSeniorPrice.setText("12");
       }
       
    }//GEN-LAST:event_jComboBoxTypeActionPerformed

    //10AM 
    private void jRadioTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioTimeActionPerformed
        // TODO add your handling code here:                                           
        // TIME OPTIONS 
         if(jLabelMovieName.getText().equals("Us")){
                    jLabelAvail.setVisible(false);
                    jLabelFull.setVisible(true);
                } 
         else if(jLabelMovieName.getText().equals("Please Lynda and Saryta")){
            jLabelAvail.setVisible(true);
            jLabelFull.setVisible(false);
        }
         else if(jLabelMovieName.getText().equals("Dumbo")){
             jLabelAvail.setVisible(true);
            jLabelFull.setVisible(false);
         }
         else if(jLabelMovieName.getText().equals("Shazam!")){
             jLabelAvail.setVisible(true);
            jLabelFull.setVisible(false);
         }
         else if(jLabelMovieName.getText().equals("Ya Nestea")){
                     jLabelAvail.setVisible(false);
                      jLabelFull.setVisible(true);
         }
        
    }//GEN-LAST:event_jRadioTimeActionPerformed
    
    //6 pm 
    private void jRadioTime2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioTime2ActionPerformed
        // TODO add your handling code here:
                if(jLabelMovieName.getText().equals("Us")){
                    jLabelAvail.setVisible(true);
                    jLabelFull.setVisible(false);
                } 
                else if(jLabelMovieName.getText().equals("Please Lynda and Saryta")){
                    jLabelAvail.setVisible(false);
                    jLabelFull.setVisible(true);
                }
                else if(jLabelMovieName.getText().equals("Dumbo")){
                    jLabelAvail.setVisible(false);
                    jLabelFull.setVisible(true);
                }
                else if(jLabelMovieName.getText().equals("Shazam!")){
                    jLabelAvail.setVisible(true);
                     jLabelFull.setVisible(false);
                     }
                else if(jLabelMovieName.getText().equals("Ya Nestea")){
                     jLabelAvail.setVisible(true);
                      jLabelFull.setVisible(false);
                    }
                
    }//GEN-LAST:event_jRadioTime2ActionPerformed

    private void jSpinnerChildInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jSpinnerChildInputMethodTextChanged
        // TODO add your handling code here
        
    }//GEN-LAST:event_jSpinnerChildInputMethodTextChanged

    private void jButtonPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPayActionPerformed
             String card = jTextCard.getText();
             String patcard= "[0-9]{16}";
             String cvc = jTextCVC.getText();
             String pattern= "[0-9][0-9][0-9]";
             String expdate= jTextExpDate.getText();
             String exppat= "^\\d{2}\\/\\d{2}$";
             
          if (!card.matches(patcard)){
           String message1 = "The card must not be blank and must have 16 digits";
            JOptionPane.showMessageDialog(null, message1);   
            }
          
            if (!cvc.matches(pattern)){
           String message1 = "The CVC must not be blank and must not contain any special characters";
            JOptionPane.showMessageDialog(null, message1);
            }
            if (!expdate.matches(exppat)){
           String message1 = "The expiry date must not be blank and must have be in the format MM//YY";
            JOptionPane.showMessageDialog(null, message1);
            }
            
            else{
                 String message1 = "Payment Succesful";
                JOptionPane.showMessageDialog(null, message1);
            }
            
    }//GEN-LAST:event_jButtonPayActionPerformed

    private void jTextCVCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCVCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCVCActionPerformed

    private void jTextCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCardActionPerformed



    /*
    // ADD COMBO BOX LISTENER FOR TYPE OF PRICES 
    void addcomboBoxListener(ItemListener listenForComboBox){
        jComboBoxType.addItemListener(listenForComboBox);
    } */
  //JComboBox comboBox = new JComboBox();
    /**
     * @param args the command line arguments
     */
   class CheckoutButtonListener implements ActionListener {
      @Override
      public void actionPerformed(ActionEvent e){
          try{
              //Contract c = theModel.getTheContract();
              //String l = c.getContractID();
              //checkout c = new checkout(theMovie, true, getTheMovie());
              //c.setLocationRelativeTo(null);
              //c.setVisible(true);
          }
          catch (Exception ex){
              System.out.println(ex);
              //theView.displayErrorMessage("Error: The numbers entered must be integers.");
          } //end catch
      } //end action 
      }//end bidbuttonListener
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonPay;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JComboBox<String> jComboBoxType;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelAdult;
    private javax.swing.JLabel jLabelAdultPrice;
    private javax.swing.JLabel jLabelAdultTotal;
    private javax.swing.JLabel jLabelAvail;
    private javax.swing.JLabel jLabelChild;
    private javax.swing.JLabel jLabelChildPrice;
    private javax.swing.JLabel jLabelChildTotal;
    private javax.swing.JLabel jLabelFull;
    private javax.swing.JLabel jLabelMovieName;
    private javax.swing.JLabel jLabelPrice;
    private javax.swing.JLabel jLabelQuantity;
    private javax.swing.JLabel jLabelRate;
    private javax.swing.JLabel jLabelRating;
    private javax.swing.JLabel jLabelSenior;
    private javax.swing.JLabel jLabelSeniorPrice;
    private javax.swing.JLabel jLabelSeniorTotal;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JLabel jLabelSubtotal;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JLabel jLabelTotalNo;
    private javax.swing.JLabel jLabelType;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioTime;
    private javax.swing.JRadioButton jRadioTime2;
    private javax.swing.JSpinner jSpinnerAdult;
    private javax.swing.JSpinner jSpinnerChild;
    private javax.swing.JSpinner jSpinnerSenior;
    private javax.swing.JTextField jTextCVC;
    private javax.swing.JTextField jTextCard;
    private javax.swing.JTextField jTextExpDate;
    // End of variables declaration//GEN-END:variables

}