/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package selectmovie;

import java.awt.event.ActionEvent;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JFrame;
import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author C0472359
 */
public class ConfirmBuy extends javax.swing.JDialog {
   
    /**
     * Creates new form java
     */
    public ConfirmBuy(JFrame f, boolean m, Movie theMovie) {
        super(f, m);
        initComponents();
        this.jLabelMovieName.setText(theMovie.getMovieName());
        this.jLabelRate.setText(theMovie.getRating());
        //this.jLabelActors.setText(theMovie.getActors()); CHECK THIS UNSURE
        //this.jLabelOrder.setText(theMovie.getOrderItem());
        /* THIS IS BIDDING NUMBERS */
        Integer startValue = 1;
        Integer minValue = 0;
        Integer maxValue = 10;
        Integer stepValue = 1;
        SpinnerModel numModel = new SpinnerNumberModel(startValue, minValue, maxValue, stepValue);
        jSpinnerChild.setModel(numModel);
        
        //int totalForChild = jSpinnerChild.getValue().toString() * 7.99;
        //String optionsFileName = System.getProperty("user.dir")+ "M:\\reyesingridj11\\SelectContract\\src\\selectcontract\\output_bids.txt";
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelMovieName = new javax.swing.JLabel();
        jLabelRate = new javax.swing.JLabel();
        jLabelActors = new javax.swing.JLabel();
        jSpinnerChild = new javax.swing.JSpinner();
        jButtonSave = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jLabelChild = new javax.swing.JLabel();
        jLabelAdult = new javax.swing.JLabel();
        jSpinnerAdult = new javax.swing.JSpinner();
        jLabelSenior = new javax.swing.JLabel();
        jSpinnerSenior = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Place bid on selected contract");
        setBackground(new java.awt.Color(255, 204, 204));

        jLabelMovieName.setText("Movie Name");

        jLabelRate.setText("Rate");

        jLabelActors.setText("Main Actors");

        jButtonSave.setText("Save");

        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jLabelChild.setText("Child");

        jLabelAdult.setText("Adult");

        jLabelSenior.setText("Senior");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelChild, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelAdult)
                            .addComponent(jLabelSenior))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSpinnerChild, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                            .addComponent(jSpinnerAdult)
                            .addComponent(jSpinnerSenior))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSave)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCancel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 10, Short.MAX_VALUE)
                .addComponent(jLabelMovieName, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                .addComponent(jLabelRate, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87)
                .addComponent(jLabelActors, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelMovieName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelRate, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabelActors, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelChild)
                    .addComponent(jSpinnerChild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAdult)
                    .addComponent(jSpinnerAdult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSpinnerSenior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSenior))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 199, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancel)
                    .addComponent(jButtonSave))
                .addGap(59, 59, 59))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/*
    private void JTextNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextNameActionPerformed
        // TODO add your handlifdfng code here:
    }//GEN-LAST:event_JTextNameActionPerformed
*/
    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        // TODO add your handling code here:
        //step 22
       //System.out.println(jSpinner1.getValue());
       
                    //REGULAR PRICES
        int childAmount = Integer.getInteger(jSpinnerChild.getValue().toString(), 100) * 8;
        String childz = jSpinnerChild.getValue().toString();
        int adultAmount= Integer.getInteger(jSpinnerAdult.getValue().toString(), 100) * 11;
        int seniorAmount = Integer.getInteger(jSpinnerSenior.getValue().toString(), 100) * 9;
        /*
        //FOR MATINEES
        int childAmount = Integer.getInteger(jSpinnerChild.getValue().toString(), 100) * 7;
        String childz = jSpinnerChild.getValue().toString();
        int adultAmount= Integer.getInteger(jSpinnerAdult.getValue().toString(), 100) * 7;
        int seniorAmount = Integer.getInteger(jSpinnerSenior.getValue().toString(), 100) * 7;
      
        //FOR TUESDAYS:
        int childAmount = Integer.getInteger(jSpinnerChild.getValue().toString(), 100) * 11;
        String childz = jSpinnerChild.getValue().toString();
        int adultAmount= Integer.getInteger(jSpinnerAdult.getValue().toString(), 100) * 15;
        int seniorAmount = Integer.getInteger(jSpinnerSenior.getValue().toString(), 100) * 12;
        
        ZonedDateTime currentDate;
        currentDate = ZonedDateTime.now();
        String dates = ZonedDateTime.now().toString();
        */
        //String filename ="\\src\\selectcontract\\output_bid.txt";
        String filename ="\\src\\selectcontract\\output_movie.txt";
        
        //THIS IS ORDER SUMMARY 
        try {
            FileWriter fileWriter = new FileWriter(filename);
            BufferedWriter br = new BufferedWriter(fileWriter);
            //customer name
            // DO WE NEED THIS? String name = JTextName.getText();
            String movieName = jLabelMovieName.getText();
            //String rate= jLabelRate.getText();
            //String total = jLabelTotal.getText();
            //String email = jTextEmail.toString();
            //br.append(name);
            br.append(movieName);
            //WE ADDED THIS 
            //br.append(email);
            //NEED TO APPEND QUANTITY AND TOTAL 
            //br.append(total);
            //br.append(bids); CHANGE
            //br.append(dates); CHANGE
            fileWriter.close();
       
        } catch(IOException ex){
            System.out.println(ex.getMessage());
        }
    
    }//GEN-LAST:event_jButtonSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JLabel jLabelActors;
    private javax.swing.JLabel jLabelAdult;
    private javax.swing.JLabel jLabelChild;
    private javax.swing.JLabel jLabelMovieName;
    private javax.swing.JLabel jLabelRate;
    private javax.swing.JLabel jLabelSenior;
    private javax.swing.JSpinner jSpinnerAdult;
    private javax.swing.JSpinner jSpinnerChild;
    private javax.swing.JSpinner jSpinnerSenior;
    // End of variables declaration//GEN-END:variables
}
